"""add_dashboard_layout_and_widget_fields

Revision ID: 47ade203cf67
Revises: add_task_alerts_table
Create Date: 2026-05-17 15:07:49.420425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47ade203cf67'
down_revision = 'add_task_alerts_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_layouts_id'), 'dashboard_layouts', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_layouts_user_id'), 'dashboard_layouts', ['user_id'], unique=False)
    op.add_column('dashboard_widget_configs', sa.Column('layout_id', sa.Integer(), nullable=True))
    op.add_column('dashboard_widget_configs', sa.Column('widget_subtype', sa.String(length=50), nullable=True))
    op.add_column('dashboard_widget_configs', sa.Column('grid_x', sa.Integer(), nullable=True))
    op.add_column('dashboard_widget_configs', sa.Column('grid_y', sa.Integer(), nullable=True))
    op.add_column('dashboard_widget_configs', sa.Column('grid_w', sa.Integer(), nullable=True))
    op.add_column('dashboard_widget_configs', sa.Column('grid_h', sa.Integer(), nullable=True))
    op.add_column('dashboard_widget_configs', sa.Column('extra_config', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_dashboard_widget_configs_layout_id'), 'dashboard_widget_configs', ['layout_id'], unique=False)
    op.create_foreign_key(None, 'dashboard_widget_configs', 'dashboard_layouts', ['layout_id'], ['id'], ondelete='CASCADE')
    op.alter_column('data_sources', 'use_proxy',
               existing_type=sa.BOOLEAN(),
               comment='是否使用代理',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('data_sources', 'proxy_server_id',
               existing_type=sa.INTEGER(),
               comment='关联的代理服务器',
               existing_nullable=True)
    op.alter_column('menus', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='菜单名称',
               existing_nullable=False)
    op.alter_column('menus', 'path',
               existing_type=sa.VARCHAR(length=200),
               comment='菜单路由路径',
               existing_nullable=True)
    op.alter_column('menus', 'icon',
               existing_type=sa.VARCHAR(length=50),
               comment='菜单图标',
               existing_nullable=True)
    op.alter_column('menus', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序顺序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('menus', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='父菜单ID',
               existing_nullable=True)
    op.alter_column('menus', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('menus', 'is_visible',
               existing_type=sa.BOOLEAN(),
               comment='是否可见',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('menus', 'remark',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment='备注',
               existing_nullable=True)
    op.alter_column('menus', 'template_id',
               existing_type=sa.INTEGER(),
               comment='关联的报表模板',
               existing_nullable=True)
    op.alter_column('menus', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('menus', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint('menus_parent_id_fkey', 'menus', type_='foreignkey')
    op.drop_constraint('menus_template_id_fkey', 'menus', type_='foreignkey')
    op.create_foreign_key(None, 'menus', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'menus', 'menus', ['parent_id'], ['id'])
    op.alter_column('prediction_models', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='软删除时间',
               existing_nullable=True)
    op.alter_column('proxy_servers', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='代理名称',
               existing_nullable=False)
    op.alter_column('proxy_servers', 'proxy_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='代理类型: http, https, socks5',
               existing_server_default=sa.text("'http'::character varying"))
    op.alter_column('proxy_servers', 'host',
               existing_type=sa.VARCHAR(length=255),
               comment='代理主机',
               existing_nullable=False)
    op.alter_column('proxy_servers', 'port',
               existing_type=sa.INTEGER(),
               comment='代理端口',
               existing_nullable=False)
    op.alter_column('proxy_servers', 'username',
               existing_type=sa.VARCHAR(length=100),
               comment='代理用户名（可选）',
               existing_nullable=True)
    op.alter_column('proxy_servers', 'password_encrypted',
               existing_type=sa.VARCHAR(length=255),
               comment='代理密码（加密存储，可选）',
               existing_nullable=True)
    op.alter_column('proxy_servers', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_proxy_servers_id'), 'proxy_servers', ['id'], unique=False)
    op.alter_column('task_alerts', 'task_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Celery 任务 ID',
               existing_nullable=False)
    op.alter_column('task_alerts', 'user_id',
               existing_type=sa.INTEGER(),
               comment='触发告警的用户 ID',
               existing_nullable=True)
    op.alter_column('task_alerts', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               comment='任务类型: export_excel/export_pdf/train_predict',
               existing_nullable=False)
    op.alter_column('task_alerts', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='告警状态: unread/read/dismissed',
               existing_nullable=False,
               existing_server_default=sa.text("'unread'::character varying"))
    op.alter_column('task_alerts', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('task_alerts', 'alert_message',
               existing_type=sa.VARCHAR(length=500),
               comment='告警摘要',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_alerts', 'alert_message',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='告警摘要',
               existing_nullable=False)
    op.alter_column('task_alerts', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('task_alerts', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='告警状态: unread/read/dismissed',
               existing_nullable=False,
               existing_server_default=sa.text("'unread'::character varying"))
    op.alter_column('task_alerts', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='任务类型: export_excel/export_pdf/train_predict',
               existing_nullable=False)
    op.alter_column('task_alerts', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='触发告警的用户 ID',
               existing_nullable=True)
    op.alter_column('task_alerts', 'task_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Celery 任务 ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_proxy_servers_id'), table_name='proxy_servers')
    op.alter_column('proxy_servers', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('proxy_servers', 'password_encrypted',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='代理密码（加密存储，可选）',
               existing_nullable=True)
    op.alter_column('proxy_servers', 'username',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='代理用户名（可选）',
               existing_nullable=True)
    op.alter_column('proxy_servers', 'port',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='代理端口',
               existing_nullable=False)
    op.alter_column('proxy_servers', 'host',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='代理主机',
               existing_nullable=False)
    op.alter_column('proxy_servers', 'proxy_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='代理类型: http, https, socks5',
               existing_server_default=sa.text("'http'::character varying"))
    op.alter_column('proxy_servers', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='代理名称',
               existing_nullable=False)
    op.alter_column('prediction_models', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='软删除时间',
               existing_nullable=True)
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.create_foreign_key('menus_template_id_fkey', 'menus', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('menus_parent_id_fkey', 'menus', 'menus', ['parent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('menus', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('menus', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('menus', 'template_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联的报表模板',
               existing_nullable=True)
    op.alter_column('menus', 'remark',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('menus', 'is_visible',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否可见',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('menus', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('menus', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='父菜单ID',
               existing_nullable=True)
    op.alter_column('menus', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('menus', 'icon',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='菜单图标',
               existing_nullable=True)
    op.alter_column('menus', 'path',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='菜单路由路径',
               existing_nullable=True)
    op.alter_column('menus', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='菜单名称',
               existing_nullable=False)
    op.alter_column('data_sources', 'proxy_server_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联的代理服务器',
               existing_nullable=True)
    op.alter_column('data_sources', 'use_proxy',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否使用代理',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'dashboard_widget_configs', type_='foreignkey')
    op.drop_index(op.f('ix_dashboard_widget_configs_layout_id'), table_name='dashboard_widget_configs')
    op.drop_column('dashboard_widget_configs', 'extra_config')
    op.drop_column('dashboard_widget_configs', 'grid_h')
    op.drop_column('dashboard_widget_configs', 'grid_w')
    op.drop_column('dashboard_widget_configs', 'grid_y')
    op.drop_column('dashboard_widget_configs', 'grid_x')
    op.drop_column('dashboard_widget_configs', 'widget_subtype')
    op.drop_column('dashboard_widget_configs', 'layout_id')
    op.drop_index(op.f('ix_dashboard_layouts_user_id'), table_name='dashboard_layouts')
    op.drop_index(op.f('ix_dashboard_layouts_id'), table_name='dashboard_layouts')
    op.drop_table('dashboard_layouts')
    # ### end Alembic commands ###
