"""add sql field to export_tasks

Revision ID: add_sql_to_export_tasks
Revises: 3e8cd2300836
Create Date: 2026-04-22 23:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_sql_to_export_tasks'
down_revision = '3e8cd2300836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_tasks', sa.Column('sql', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_tasks', 'sql')
    # ### end Alembic commands ###
